### ISSUE TITLE
import template error

### ISSUE THREAD

**Issue by ramarajana** [leighlatham123/zabbix-cloudwatch#1]
Invalid parameter "/13/params": incorrect expression starting from "last("cloudwatch.metric["--i", "600","--m", "FreeStorageSpace","--n", "AWS/RDS","--s", "Average","--r", "{$REGION}","--dimension", "DBInstanceIdentifier={#RDS_ID}","--a", "{$ACCOUNT}"]")/({#STORAGE}/100)".

**Comment by leighlatham123** [comment]
hey @ramarajana what version of Zabbix specifically are you attempting to import to? We're still using v4.4.8 as we haven't had the opportunity to upgrade.

I'd be happy to try help you get this working, I just may need a bit more info.

**Comment by ramarajana** [comment]
hi @leighlatham123 thanks for your reply, i am using zabbix v5.4, can i try this in zabbix-release_4.4-1+bionic_all.deb  and then connect you it is ok

**Comment by leighlatham123** [comment]
Hey, @ramarajana apologies can I please just clarify, are you saying you are going to try this on the 4.4 release or you already have and it's working?

I think the issue may be that the templating engine has changed syntax for 5.x and I need to update this to match. I can work on that soon.

**Comment by ramarajana** [comment]
@leighlatham123 I haven't done in 4.4 as you said you are using Zabbix 4.4, so only I am saying can I try this in 4.4 will it work?

**Comment by leighlatham123** [comment]
Hey @ramarajana so providing you are following the steps outlined in my readme it should work, as that's what we did to integrate AWS with Zabbix.

This is the image we used https://github.com/zabbix/zabbix-docker - but the image should not matter, along as the version you are using in the container matches ours - which is 4.4.8.

From the error snippet you provided, this looks to have been an unsupported change recognised during the template import, which I can only assume currently is because of the later version of Zabbix not supporting this template syntax (I had to edit the template from the forked repo for the same reason to update the template as 4.x did not support the old syntax).

Please give it a try and let me know, I will help you get this working.

**Comment by leighlatham123** [comment]
If needs be, i'll temporarily host a 5.x version (we aren't ready to upgrade at my company) and will try to replicate your issue. But if it works on 4.x for you, I can delay doing that for a bit longer :)

**Comment by ramarajana** [comment]
ok, I will try this and update you.
Thanks for your help.

**Comment by leighlatham123** [comment]
hey @ramarajana just following up to see if you had a chance to test this yet?

**Comment by leighlatham123** [comment]
hey @ramarajana sorry to keep chasing just interested in how you got on with this. I'm aware I'll need to update this script for the latest Zabbix so if you've gone with another implementation or have lost interest I'll close the issue and update the code accordingly in due course.
